inherit_from: .rubocop_todo.yml

AllCops:
  Excludes:
    - "node_modules/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - ".git/**/*"

  SuggestExtensions: false

Layout/EndOfLine:
  Enabled: false
# Metrics/AbcSize:
#   Max: 42

# Configuration parameters: CountComments, CountAsOne, ExcludedMethods, IgnoredMethods.
# IgnoredMethods: refine
Metrics/BlockLength:
  Max: 100

# # Configuration parameters: IgnoredMethods.
# Metrics/CyclomaticComplexity:
#   Max: 9

# Configuration parameters: CountComments, CountAsOne, ExcludedMethods, IgnoredMethods.
Metrics/MethodLength:
  Max: 100

# Configuration parameters: IgnoredMethods.
Metrics/PerceivedComplexity:
  Max: 10
# # Offense count: 3
# # Cop supports --auto-correct.
# # Configuration parameters: AutoCorrect, AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, IgnoredPatterns.
# # URISchemes: http, https
# Layout/LineLength:
#   Max: 200
