inherit_from: .rubocop_todo.yml

AllCops:
  Excludes:
    - "node_modules/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - ".git/**/*"
    - "bin/**/*"

  SuggestExtensions: false

Layout/EndOfLine:
  Enabled: false

Metrics/AbcSize:
  Max: 45

# Configuration parameters: CountComments, CountAsOne, ExcludedMethods, IgnoredMethods.
# IgnoredMethods: refine
Metrics/BlockLength:
  Max: 100

Metrics/CyclomaticComplexity:
  Max: 10

# Configuration parameters: CountComments, CountAsOne, ExcludedMethods, IgnoredMethods.
Metrics/MethodLength:
  Max: 100

# Configuration parameters: IgnoredMethods.
Metrics/PerceivedComplexity:
  Max: 10

# URISchemes: http, https
Layout/LineLength:
  Max: 150
