inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - "node_modules/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - ".git/**/*"
    - "bin/**/*"
    - "spec/**/*"
    - "app/controllers/personalities_controller.rb"
    - "app/views/personalities/**"
    - "db/schema.rb"
    - "app/dashboards/**"
  NewCops: disabled

Layout/EndOfLine:
  Enabled: false

Metrics/AbcSize:
  Max: 90

# Configuration parameters: CountComments, CountAsOne, ExcludedMethods, IgnoredMethods.
# IgnoredMethods: refine
Metrics/BlockLength:
  Max: 100

Metrics/CyclomaticComplexity:
  Max: 15

# Configuration parameters: CountComments, CountAsOne, ExcludedMethods, IgnoredMethods.
Metrics/MethodLength:
  Max: 100

# Configuration parameters: IgnoredMethods.
Metrics/PerceivedComplexity:
  Max: 20

# URISchemes: http, https
Layout/LineLength:
  Max: 155

Style/HashEachMethods:
  Enabled: false

Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues:
  Enabled: false
